name: golangci-lint-langserver
version: 2026.01.17 
title: golangci-lint language server
summary: Language Server for golangci-lint
description: |
  A Language Server Protocol server for Go, using golangci-lint.
contact: brett.holman@canonical.com
license: MIT
base: core24
grade: stable
confinement: strict
website: https://github.com/nametake/golangci-lint-langserver
source-code: https://github.com/nametake/golangci-lint-langserver
issues: https://github.com/nametake/golangci-lint-langserver/issues

apps:
  golangci-lint-langserver:
    command: bin/golangci-lint-langserver
    plugs: [home, network]
    environment:
      PATH: $SNAP/usr/bin:$PATH
      GOCACHE: $SNAP_USER_COMMON/.cache/go-build
      GOPATH: $SNAP_USER_COMMON/go
  golangci-lint:
    command: bin/golangci-lint
  go:
    command: usr/bin/go

parts:
  golangci-lint-langserver:
    plugin: go
    source: https://github.com/nametake/golangci-lint-langserver.git
    source-tag: v0.0.11
    build-packages:
      - golang-go
    stage-packages:
      - golang-go
    after: [golangci-lint]

  golangci-lint:
    plugin: nil
    stage-snaps: [golangci-lint]
    organize:
      golangci-lint: bin/golangci-lint
    prime:
      - bin/golangci-lint
